site_name: Revista Darcy

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: green
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: green
      accent: #8ECDDD
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Ínicio: index.md
  - Requisitos:
    - Visão de Produto: visao_de_produto.md
    - Visão de Projeto: visao_de_projeto.md
  - Documentação Interna:
    - Políticas Internas: 
      - Branches: politicas/branches.md
      - Commit: politicas/commit.md
      - Conduta: politicas/conduta.md
      - Plano de Comunicação: politicas/plano-de-comunicacao.md
    - Sprints:
      - Sprint 00: 
        - Planejamento: sprints/sprint00/planejamento.md
        - Resultados: sprints/sprint00/resultados.md