site_name: Revista Darcy

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
      primary: green
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro  
      primary: green
      accent: #8ECDDD
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Ínicio: index.md
  - Requisitos:
    - Visão de Produto: requisitos/visao_de_produto.md
    - Visão de Projeto: requisitos/visao_de_projeto.md
    - Backlog: requisitos/backlog.md
    - Perfil dos Usuários: requisitos/perfil_dos_usuarios.md
  - Documentação Interna:
    - Políticas Internas: 
      - Branches: politicas/branches.md
      - Commit: politicas/commit.md
      - Conduta: politicas/conduta.md
      - Plano de Comunicação: politicas/plano-de-comunicacao.md
    - Sprints:
      - Sprint 00: 
        - Planejamento: sprints/sprint00/planejamento.md
        - Resultados: sprints/sprint00/resultados.md
      - Sprint 01: 
        - Planejamento: sprints/sprint01/planejamento.md
        - Resultados: sprints/sprint01/resultados.md
      - Sprint 02: 
        - Planejamento: sprints/sprint02/planejamento.md
        - Resultados: sprints/sprint02/resultados.md
      - Sprint 03: 
        - Planejamento: sprints/sprint03/planejamento.md
        - Resultados: sprints/sprint03/resultados.md
      - Sprint 04:
        - Planejamento: sprints/sprint04/planejamento.md
        - Resultados: sprints/sprint04/resultados.md
      - Sprint 05:
        - Planejamento: sprints/sprint05/planejamento.md
        - Resultados: sprints/sprint05/resultados.md
      - Sprint 06:
        - Planejamento: sprints/sprint06/planejamento.md
        - Resultados: sprints/sprint06/resultados.md
      - Sprint 07:
        - Planejamento: sprints/sprint07/planejamento.md
        - Resultados: sprints/sprint07/resultados.md
      - Sprint 08:
        - Planejamento: sprints/sprint08/planejamento.md
        - Resultados: sprints/sprint08/resultados.md
      - Sprint 09:
        - Planejamento: sprints/sprint09/planejamento.md
        - Resultados: sprints/sprint09/resultados.md
    - Atas:
      - Reuniões Internas:
        - Reunião 0: atas/equipe/ata00.md
        - Reunião 1: atas/equipe/ata01.md
        - Reunião 2: atas/equipe/ata02.md
        - Reunião 3: atas/equipe/ata03.md
        - Reunião 4: atas/equipe/ata04.md
        - Reunião 5: atas/equipe/ata05.md
        - Reunião 6: atas/equipe/ata06.md
        - Reunião 7: atas/equipe/ata07.md
        - Reunião 8: atas/equipe/ata08.md
        - Reunião 9: atas/equipe/ata09.md
      - Reuniões com o Cliente:
        - Reunião 1: atas/equipe_cliente/ata01.md
        - Reunião 2: atas/equipe_cliente/ata02.md
        - Reunião 3: atas/equipe_cliente/ata03.md
        - Reunião 4: atas/equipe_cliente/ata04.md
        - Reunião 5: atas/equipe_cliente/ata05.md
        - Reunião 6: atas/equipe_cliente/ata06.md
        - Reunião 7: atas/equipe_cliente/ata07.md
        - Reunião 8: atas/equipe_cliente/ata08.md
        - Reunião 9: atas/equipe_cliente/ata09.md
        - Reunião 10: atas/equipe_cliente/ata10.md
        - Reunião 11: atas/equipe_cliente/ata11.md
  - Releases:
    - Release 1: release/release1.md
      